<a href="https://colab.research.google.com/github/Nathan0820/ml_projects/blob/main/irisFlower_classifier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [35]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

In [36]:
iris_dataset = pd.read_csv('IRIS.csv')
print(iris_dataset.head())

   sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa


In [37]:
print(iris_dataset.shape)

(150, 5)


In [38]:
print(iris_dataset['species'].unique())

['Iris-setosa' 'Iris-versicolor' 'Iris-virginica']


In [39]:
print(iris_dataset.isnull().sum())

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64


In [40]:
X = iris_dataset.drop('species', axis=1)
y = iris_dataset['species']

In [41]:
print(X.shape)
print(y.shape)

(150, 4)
(150,)


In [42]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, stratify=y, random_state=42)

In [43]:
model = LogisticRegression()
model.fit(X_train, y_train)
preds = model.predict(X_test)

In [44]:
accuracy = accuracy_score(y_test, preds)
print(confusion_matrix(y_test, preds))
print(classification_report(y_test, preds))
print(accuracy)

[[10  0  0]
 [ 0  9  1]
 [ 0  0 10]]
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        10
Iris-versicolor       1.00      0.90      0.95        10
 Iris-virginica       0.91      1.00      0.95        10

       accuracy                           0.97        30
      macro avg       0.97      0.97      0.97        30
   weighted avg       0.97      0.97      0.97        30

0.9666666666666667


In [45]:
sample = (5, 3.6, 1.4, 0.2)
input_as_np_array = np.asarray(sample)
input_reshaped = input_as_np_array.reshape(1, -1)
prediction = model.predict(input_reshaped)
print(prediction)

['Iris-setosa']


/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
